CREATE DATABASE IF NOT EXISTS portfolio_db;
USE portfolio_db;


CREATE TABLE IF NOT EXISTS skills (
id INT AUTO_INCREMENT PRIMARY KEY,
subject VARCHAR(100) NOT NULL,
level INT DEFAULT 0,
logo VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS experience (
id INT AUTO_INCREMENT PRIMARY KEY,
company VARCHAR(100) NOT NULL,
role VARCHAR(100) NOT NULL,
period VARCHAR(100),
points TEXT
);


CREATE TABLE IF NOT EXISTS projects (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150) NOT NULL,
url VARCHAR(255),
description TEXT,
skills VARCHAR(255)
);